# Generated by Django 3.0.8 on 2020-07-25 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_group_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_by', models.DateField(blank=True, null=True)),
                ('date_administered', models.DateField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=200)),
                ('certified_by', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('disease_type', models.CharField(max_length=200)),
                ('required_doses', models.CharField(max_length=200)),
                ('required_country', models.CharField(max_length=200)),
                ('reccomended_age', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(default=None)),
                ('phone_number', models.CharField(max_length=200)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('doctor_name_contact', models.CharField(blank=True, max_length=200)),
                ('blood_type', models.CharField(blank=True, max_length=500)),
                ('allergies', models.CharField(blank=True, max_length=200)),
                ('existing_health_conditions', models.CharField(blank=True, max_length=200)),
                ('familygroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FamilyGroup')),
                ('immunization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Immunization')),
            ],
        ),
        migrations.AddField(
            model_name='immunization',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vaccine'),
        ),
    ]
