# Generated by Django 3.0.8 on 2020-07-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='immunization',
        ),
        migrations.AddField(
            model_name='immunization',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='vaccine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Vaccine'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='familygroup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.FamilyGroup'),
        ),
    ]
