# Generated by Django 3.0.8 on 2020-07-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200725_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isChild',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isParent',
            field=models.BooleanField(default=False),
        ),
    ]
