# Generated by Django 3.0.8 on 2020-08-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200802_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family_member_type',
            field=models.CharField(blank=True, choices=[('PARENT', 'parent'), ('CHILD', 'child'), ('OTHER', 'other')], max_length=200),
        ),
    ]
