# Generated by Django 3.0.8 on 2020-08-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200802_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family_member_type',
            field=models.CharField(blank=True, choices=[('Parent', 'parent'), ('Child', 'child'), ('Other', 'other')], max_length=200),
        ),
    ]
