# Generated by Django 3.0.8 on 2020-08-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200802_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A RhD positive A+', 'A RhD positive A+'), ('A RhD negative A-', 'A RhD negative A-'), ('B RhD positive B+', 'B RhD positive B+'), ('B RhD negative B-', 'B RhD negative B-'), ('O RhD positive O+', 'O RhD positive O+'), ('O RhD negative O-', 'O RhD negative O-'), ('AB RhD positive AB+', 'AB RhD positive AB+'), ('AB RhD negative AB-', 'AB RhD negative AB-')], max_length=500),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_name',
            field=models.CharField(max_length=200),
        ),
    ]
