# Generated by Django 3.0.8 on 2020-08-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200802_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family_member_type',
            field=models.CharField(blank=True, choices=[('Parent', 'Parent'), ('Child', 'Child'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='disease_type',
            field=models.CharField(blank=True, choices=[('Diptheria', 'Diptheria'), ('Hepatitis B', 'Hepatitis B'), ('Haemophilus influenzae type b', 'Haemophilus influenzae type b'), ('Human papillomavirus', 'Human papillomavirus'), ('Seasonal influenza', 'Seasonal influenza'), ('Measles', 'Measles'), ('Mumps', 'Mumps'), ('Pertussis (Whooping Cough)', 'Pertussis (Whooping Cough)'), ('Rubella', 'Rubella'), ('Pneumococcal disease', 'Pneumococcal disease'), ('Poliomyelitis (Polio)', 'Poliomyelitis (Polio)'), ('Rotavirus', 'Rotavirus'), ('Tetanus', 'Tetanus'), ('Tuberculosis (TB)', 'Tuberculosis (TB)'), ('Varicella', 'Varicella')], max_length=200),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='recommended_age',
            field=models.CharField(blank=True, choices=[('0-1 yrs', '0-1 yrs'), ('1-5 yrs', '1-5 yrs'), ('6-10 yrs', '6-10 yrs'), ('Any Age', 'Any Age')], max_length=200),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='required_country',
            field=models.CharField(blank=True, choices=[('Africa', 'Africa'), ('United States', 'United States'), ('Mexico', 'Mexico'), ('Switzerland', 'Switzerland')], max_length=200),
        ),
    ]
