# Generated by Django 3.0.8 on 2020-08-06 20:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_vaccine_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vaccine_card_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
