# Generated by Django 3.0.9 on 2020-08-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_notifyuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotifyUser',
        ),
    ]
