# Generated by Django 3.0.8 on 2020-08-23 14:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200822_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
