# Generated by Django 3.0.8 on 2020-08-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200823_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
