# Generated by Django 3.0.9 on 2020-08-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200823_1421'),
        ('app', '0015_delete_notifyuser'),
    ]

    operations = [
    ]
